version: 2

build:
  os: ubuntu-20.04
  image: latest

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py
