name: ci
on:
  pull_request:
    branches: [main]

jobs:
  run_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry==1.2.2
          poetry install

      - name: Linting
        run: |
          poetry run pre-commit run --all-files

  run_testing:
    runs-on: ubuntu-latest
    needs: run_linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry==1.2.2
          poetry install

      - name: Run tests
        env:
          environment: main
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: 755f6e58-74f0-4a07-a599-f7479b9669ab
          COGNITE_PROJECT: oceandata-dev
          CDF_CLUSTER: westeurope-1
        run: |
          poetry run pytest tests/ -v --cov-report xml:coverage.xml --cov
          poetry run coverage xml

      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
